app/app/urls.py
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name='api-schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='api-schema'), name='api-docs'),
    path('', include('user.urls')),
    path('', include('post.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/post/urls.py
"""
URL mappings for the post app.
"""
from django.urls import (
    path,
    include,
)

from rest_framework.routers import DefaultRouter

from post import views  # noqa

router = DefaultRouter()
router.register('posts', views.PostViewSet)
router.register('tags', views.TagViewSet)
router.register('hashtags', views.HashTagViewSet)

app_name = 'post'

# API ROUTE
urlpatterns = [
    path('api/post/', include(router.urls)),
]

# WEB PAGE ROUTE
urlpatterns += [
    path('', views.IndexListView.as_view(), name='index'),
    path('post/create/', views.CreatePostView.as_view(), name='create'),
    path('post/update/<int:pk>', views.UpdatePostView.as_view(), name='update'),
    path('post/delete/<int:pk>', views.DeletePostView.as_view(), name='delete'),
    path('post/like-post/', views.like_post, name='like-post'),
    path('post/comment-post/', views.comment_post, name='comment-post'),
    path('post/comment-post-update/', views.comment_post_update, name='comment-post-update'),
    path('post/comment-post-delete/', views.comment_post_delete, name='comment-post-delete'),
]

app/user/urls.py
"""
URL mappings for the user API.
"""
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from user import views  # noqa

app_name = 'user'

# API ROUTE
urlpatterns = [
    path('api/user/create/', views.CreateUserView.as_view(), name='create'),
    path('api/user/token/', views.CreateTokenView.as_view(), name='token'),
    path('api/user/me/', views.ManageUserView.as_view(), name='me'),
]

# WEB PAGE ROUTE
urlpatterns += [
    path('signup/', views.RegisterUserView.as_view(), name="signup"),
    path('login/', views.LoginUserView.as_view(), name="login"),
    path("logout/", login_required(LogoutView.as_view(template_name="authentication/logout.html")),
         name="logout"),
    path('profile/<str:username>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<str:username>/update/', views.ProfileUpdateView.as_view(),
         name='profile-update'),
    path('follow/user/', views.follow, name='follow'),
]

app/post/forms.py
"""
Forms for the Post views
"""

from django import forms
from core.models import Post, Tag, Comment # noqa
from django.contrib.auth import get_user_model


class PostCreateForm(forms.ModelForm):
    """Form to create post."""
    title = forms.CharField(widget=forms.TextInput(
        attrs={"placeholder": "Title", "class": "form-control"}))
    body = forms.Textarea()
    img = forms.ImageField()

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(PostCreateForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Post
        fields = ['title', 'body', "img"]

    def save(self, commit=True):
        instance = super(PostCreateForm, self).save(commit=False)
        instance.user = self.user

        tags_in_post_title = [{"somebody": word[1:]} for word in instance.title.split(" ")
                              if word[0] == "@" and get_user_model().objects.filter(username=word[1:]).exists()]

        tags_in_post_body = [{"somebody": word[1:]} for word in instance.body.split(" ")
                             if word[0] == "@" and get_user_model().objects.filter(username=word[1:]).exists()]

        if commit:
            instance.save()

        post_tags = tags_in_post_title + tags_in_post_body

        try:
            tag_id = Tag.objects.all().order_by("-id")[0].id
        except IndexError:
            tag_id = 0

        if post_tags:
            for tag in post_tags:
                tag_obj, created = Tag.objects.get_or_create(
                    id=tag_id,
                    user=self.user,
                    **tag,
                )
                instance.tags.add(tag_obj)
                tag_id += 1

        return instance


class PostUpdateForm(PostCreateForm):
    """Form to create post."""


class CommentCreateForm(forms.ModelForm):
    """Form to create comment on a post."""
    body = forms.Textarea()

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(CommentCreateForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Comment
        fields = ['body', "post"]

    def save(self, commit=True):
        instance = super(CommentCreateForm, self).save(commit=False)
        instance.user = self.user
        print(instance)
        if commit:
            instance.save()

        return instance

app/post/views.py
"""
Views for the recipe APIs
"""
from django.contrib.auth.decorators import login_required
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404
from drf_spectacular.utils import (
    extend_schema_view,
    extend_schema,
    OpenApiParameter,
    OpenApiTypes,
)

from rest_framework import (viewsets, status, mixins)
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from django import views
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from core.models import Post, HashTag, Tag, Like, Comment  # noqa
from post import serializers  # noqa
from .forms import PostCreateForm, PostUpdateForm


# WEB PAGE POST VIEWS
class IndexListView(LoginRequiredMixin, views.generic.ListView):
    """Home page."""
    queryset = Post.objects.all()
    template_name = "home/content.html"
    context_object_name = "posts"

    def get_queryset(self):
        """Retrieve posts for authenticated user."""
        queryset = self.queryset

        return queryset.all()

    def get_context_data(self, **kwargs):
        context = super(IndexListView, self).get_context_data(**kwargs)
        posts = self.get_queryset().filter(user=self.request.user)

        liked = []
        for post in posts:
            if post.likes.filter(user=self.request.user).exists():
                liked.append(post.id)

        context['liked'] = liked

        return context


class CreatePostView(LoginRequiredMixin, views.generic.CreateView):
    """User registration view."""
    model = Post
    form_class = PostCreateForm
    template_name = 'home/post-create.html'

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)  # noqa
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse_lazy('post:index')


class UpdatePostView(LoginRequiredMixin, views.generic.UpdateView):
    """Views for the profile page."""
    model = Post
    form_class = PostUpdateForm
    template_name = 'home/post-update.html'

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)  # noqa
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse_lazy('post:index')

    def get_object(self, **kwargs):
        """Get the object specific to the user."""
        pk = self.kwargs.get("pk", None)

        if pk is None:
            raise Http404
        return get_object_or_404(Post, id=pk, user=self.request.user)

    def get_context_data(self, **kwargs):
        """Set the form values before rendering on the page"""
        context = super().get_context_data(**kwargs)
        post = self.get_object()

        data = {
            'title': post.title,
            'body': post.body,
            'img': post.img,
        }

        form = self.form_class(initial=data, user=post.user)

        context['form'] = form

        return context


@login_required
def comment_post(request):
    """Like a post."""
    if request.method == 'POST' and request.user.is_authenticated:
        pk = request.POST.get("post_id")
        body = request.POST.get("body")
        post = get_object_or_404(Post, pk=pk)

        if post:
            Comment.objects.create(user=request.user, post=post, body=body)
            post.save()
            comment = post.comments.filter(user=request.user).first()
            return JsonResponse({'success': True, 'comment_body': comment.body,
                                 "created_at": comment.created_at})

    return JsonResponse({}, status=400)


@login_required
def comment_post_update(request):
    """Like a post."""
    if request.method == 'POST' and request.user.is_authenticated:
        pk = request.POST.get("comment_id")
        body = request.POST.get("body")
        comment = get_object_or_404(Comment, user=request.user, pk=pk)

        if comment:
            comment.body = body
            comment.save()

            return JsonResponse({'success': True, 'comment_body': comment.body,
                                 "updated_at": comment.updated_at})

    return JsonResponse({}, status=400)


@login_required
def comment_post_delete(request):
    """Delete comment from a post."""
    if request.method == 'POST' and request.user.is_authenticated:
        pk = request.POST.get("comment_id")
        comment = get_object_or_404(Comment, user=request.user, pk=pk)

        if comment:
            comment.delete()

            return JsonResponse({'success': True, 'message': "Comment was deleted successfully."})

    return JsonResponse({}, status=400)


@login_required
def like_post(request):
    """Like a post."""
    if request.method == 'POST' and request.user.is_authenticated:
        pk = request.POST.get("post_id")
        post = get_object_or_404(Post, pk=pk)

        if not post.likes.filter(user=request.user).exists():
            Like.objects.create(user=request.user, post=post)
            post.likes_count += 1
            post.save()

            return JsonResponse({'success': True, 'new_like_count': post.likes_count})
        else:
            Like.objects.filter(user=request.user, post=post).delete()
            post.likes_count -= 1
            post.save()

            return JsonResponse({'success': True, 'new_like_count': post.likes_count})

    return JsonResponse({}, status=400)


class DeletePostView(LoginRequiredMixin, views.generic.DeleteView):
    model = Post
    template_name = 'home/post-delete.html'

    def get_success_url(self):
        return reverse_lazy('post:index')

    def get_object(self, **kwargs):
        """Get the object specific to the user."""
        pk = self.kwargs.get("pk", None)

        if pk is None:
            raise Http404
        return get_object_or_404(Post, id=pk, user=self.request.user)


# API VIEWS
@extend_schema_view(
    list=extend_schema(
        parameters=[
            OpenApiParameter(
                'hashtags',
                OpenApiTypes.STR,
                description='Comma separated list of hashtag IDs to filter',
            ),
            OpenApiParameter(
                'tags',
                OpenApiTypes.STR,
                description='Comma separated list of tags IDs to filter',
            ),
        ]
    )
)
class PostViewSet(viewsets.ModelViewSet):
    """View for managing post APIs."""
    serializer_class = serializers.PostSerializer
    queryset = Post.objects.all()
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

    def _params_to_ints(self, qs):
        """Convert a list of strings to integers."""
        return [int(str_id) for str_id in qs.split(',')]

    def get_queryset(self):
        """Retrieve posts for authenticated user."""
        hashtags = self.request.query_params.get('hashtags')
        queryset = self.queryset

        if hashtags:
            hashtags_ids = self._params_to_ints(hashtags)
            queryset = queryset.filter(hashtags__id__in=hashtags_ids)

        return queryset.filter(
            user=self.request.user
        ).order_by('-id').distinct()

    def get_serializer_class(self):
        """Return the serializer class for request."""
        if self.action == 'list':
            return serializers.PostSerializer
        elif self.action == 'upload_image':
            return serializers.PostImageSerializer

        return self.serializer_class

    def perform_create(self, serializer):
        """Create a new post."""
        serializer.save(user=self.request.user)

    @action(methods=['POST'], detail=True, url_path='upload-image')
    def upload_image(self, request, pk=None):
        """Upload an image to post."""
        post = self.get_object()
        serializer = self.get_serializer(post, data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@extend_schema_view(
    list=extend_schema(
        parameters=[
            OpenApiParameter(
                'assigned_only',
                OpenApiTypes.INT, enum=[0, 1],
                description='Filter by items assigned posts.',
            ),
        ]
    )
)
class BasePostAttrViewSet(mixins.DestroyModelMixin,
                          mixins.UpdateModelMixin,
                          mixins.ListModelMixin,
                          viewsets.GenericViewSet):
    """Base viewset for post attributes."""
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Filter queryset to authenticated user."""
        assigned_only = bool(
            int(self.request.query_params.get('assigned_only', 0))
        )
        queryset = self.queryset

        if assigned_only:
            queryset = queryset.filter(post__isnull=False)

        return queryset.filter(
            user=self.request.user).order_by('-name').distinct()


@extend_schema_view(
    list=extend_schema(
        parameters=[
            OpenApiParameter(
                'assigned_only',
                OpenApiTypes.INT, enum=[0, 1],
                description='Filter by items assigned posts.',
            ),
        ]
    )
)
class TagBasePostAttrViewSet(mixins.DestroyModelMixin,
                             mixins.UpdateModelMixin,
                             mixins.ListModelMixin,
                             viewsets.GenericViewSet):
    """Base viewset for post attributes."""
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Filter queryset to authenticated user."""

app/core/templates/home/birthdays.html
<div class="card">
    <div class="card-header d-flex justify-content-between">
        <div class="header-title">
            <h4 class="card-title">Upcoming Birthday</h4>
        </div>
    </div>
    <div class="card-body">
        <ul class="media-story list-inline m-0 p-0">
            <li class="d-flex mb-4 align-items-center">
                <img src="static/static/assets/images/user/01.jpg" alt="story-img"
                     class="rounded-circle img-fluid">
                <div class="stories-data ms-3">
                    <h5>Anna Sthesia</h5>
                    <p class="mb-0">Today</p>
                </div>
            </li>
            <li class="d-flex align-items-center">
                <img src="static/static/assets/images/user/02.jpg" alt="story-img"
                     class="rounded-circle img-fluid">
                <div class="stories-data ms-3">
                    <h5>Paul Molive</h5>
                    <p class="mb-0">Tomorrow</p>
                </div>
            </li>
        </ul>
    </div>
</div>

app/core/templates/home/content.html
{% extends "layouts/base.html" %}

{% block title %}AmosNet{% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}

<div id="content-page" class="content-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 row m-0 p-0">
                {% include 'home/create.html' %}
                {% include 'home/post.html' %}
            </div>
            <div class="col-lg-4">
                {% include 'home/suggested.html' %}
                {% include 'home/trending.html' %}
                {% include 'home/birthdays.html' %}
                {% include 'home/resent_post.html' %}
            </div>
            <div class="col-sm-12 text-center">
                <img src="static/static/assets/images/page-img/page-load-loader.gif" alt="loader"
                     style="height: 100px;">
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

app/core/templates/home/index.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{% url 'post:create' %}">
    <button>CREATE POST</button>
</a>
<a href="{% url 'user:profile' username=request.user %}">
    <button>PROFILE</button>
</a>
<a href="{% url 'user:logout' %}">
    <button>LOGOUT</button>
</a>

<h1>Feed Home Page.</h1>

{% for post in posts %}
<div class="row">
    <div class="col-md-6">
        {{ post.title }}
        <a href="{% url 'post:update' pk=post.pk %}">
            <button>UPDATE POST</button>
        </a>
        <a href="{% url 'post:delete' pk=post.pk %}">
            <button>DELETE POST</button>
        </a>
    </div>
    {% if post.id in liked %}
    <img src="{% static 'default_image/liked.png'%}" width="30" height="30" alt="like" id="{{ post.id }}"
         class="likeBtn img_{{ post.id }}">
    {% else %}
    <img src="{% static 'default_image/disliked.png'%}" width="30" height="30" alt="like" id="{{ post.id }}"
         class="likeBtn img_{{ post.id }}">
    {% endif  %}

    <div id="likeCount_{{ post.id }}">Likes: {{ post.likes_count }}</div>
</div>
<hr>
{% endfor %}

</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!--Likes jQ-->
<script>
window.CSRF_TOKEN ="{{ csrf_token }}"
$(document).ready(function() {
    $('.likeBtn').on('click', function() {
        var post_id = this.id
        var oldImage = $(`.img_${post_id}`).attr('src')

        var liked = '{% static 'default_image/liked.png' %}';
        var disliked = '{% static 'default_image/disliked.png' %}';

        console.log(oldImage)

        $.ajax({
            type: 'POST',
            url: '{% url "post:like-post" %}',
            data:{
                post_id: post_id,
                csrfmiddlewaretoken:window.CSRF_TOKEN
                },
            beforeSend: function(xhr) {
                  if (oldImage == liked) {
                    $(`.img_${post_id}`).attr('src', disliked);
                } else {
                    $(`.img_${post_id}`).attr('src', liked);
                }
            },
            success: function(response) {
                if (response.success) {
                    $(`#likeCount_${post_id}`).text('Likes: ' + response.new_like_count);
                } else {
                    alert('Failed to like the post: ' + response.error);
                }
            },
            error: function(xhr, status, error) {
                alert('Error: ' + error);
            }
        });
    });
});

</script>

</html>

app/core/templates/home/post-create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>POST CREATE</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button>submit</button>
</form>

</body>
</html>

app/core/templates/home/post-delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>POST DELETE</h1>
<h5>Are you sure you want to delete this post? <a href="{% url 'post:index' %}">NO</a></h5>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <button>YES</button>
</form>

</body>
</html>

app/core/templates/home/post-update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>POST UPDATE</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button>submit</button>
</form>

</body>
</html>

app/core/templates/home/profile-update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>PROFILE UPDATE</h1>

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button>submit</button>
</form>

</body>
</html>

app/core/templates/home/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>PROFILE</h1>
<h5>{{ request.user }}</h5>
</body>
</html>

app/core/templates/home/resent_post.html
<div class="card">
    <div class="card-header d-flex justify-content-between">
        <div class="header-title">
            <h4 class="card-title">Your Recent Post</h4>
        </div>
        <div class="card-header-toolbar d-flex align-items-center">
            <div class="dropdown">
                <div class="dropdown-toggle" id="dropdownMenuButton01" data-bs-toggle="dropdown"
                     aria-expanded="false" role="button">
                    <i class="ri-more-fill h4"></i>
                </div>
                <div class="dropdown-menu dropdown-menu-right"
                     aria-labelledby="dropdownMenuButton01">
                    <a class="dropdown-item" href="#"><i class="ri-eye-fill me-2"></i>View</a>
                    <a class="dropdown-item" href="#"><i
                            class="ri-delete-bin-6-fill me-2"></i>Delete</a>
                    <a class="dropdown-item" href="#"><i class="ri-pencil-fill me-2"></i>Edit</a>
                    <a class="dropdown-item" href="#"><i class="ri-printer-fill me-2"></i>Print</a>
                    <a class="dropdown-item" href="#"><i class="ri-file-download-fill me-2"></i>Download</a>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <ul class="suggested-page-story m-0 p-0 list-inline">
            <li class="mb-3">
                <div class="d-flex align-items-center mb-3">
                    <img src="static/static/assets/images/page-img/42.png" alt="story-img"
                         class="rounded-circle img-fluid avatar-50">
                    <div class="stories-data ms-3">
                        <h5>Iqonic Studio</h5>
                        <p class="mb-0">Lorem Ipsum</p>
                    </div>
                </div>
                <img src="static/static/assets/images/small/img-1.jpg" class="img-fluid rounded"
                     alt="Responsive image">
                <div class="mt-3"><a href="#" class="btn d-block"><i
                        class="ri-thumb-up-line me-2"></i> Like Page</a></div>
            </li>
            <li class="">
                <div class="d-flex align-items-center mb-3">
                    <img src="static/static/assets/images/page-img/42.png" alt="story-img"
                         class="rounded-circle img-fluid avatar-50">
                    <div class="stories-data ms-3">
                        <h5>Cakes & Bakes </h5>
                        <p class="mb-0">Lorem Ipsum</p>
                    </div>
                </div>
                <img src="static/static/assets/images/small/img-2.jpg" class="img-fluid rounded"
                     alt="Responsive image">
                <div class="mt-3"><a href="#" class="btn d-block"><i
                        class="ri-thumb-up-line me-2"></i> Like Page</a></div>
            </li>
        </ul>
    </div>
</div>

app/core/templates/home/suggested.html
<div class="card">
    <div class="card-header d-flex justify-content-between">
        <div class="header-title">
            <h4 class="card-title">Follow</h4>
        </div>
    </div>
    <div class="card-body">
        <ul class="media-story list-inline m-0 p-0">
            <li class="d-flex mb-3 align-items-center active">
                <img src="static/static/assets/images/page-img/s2.jpg" alt="story-img"
                     class="rounded-circle img-fluid">
                <div class="stories-data ms-3">
                    <h5>Anna Mull</h5>
                    <p class="mb-0">Developer</p>
                </div>
            </li>
            <li class="d-flex mb-3 align-items-center">
                <img src="static/static/assets/images/page-img/s3.jpg" alt="story-img"
                     class="rounded-circle img-fluid">
                <div class="stories-data ms-3">
                    <h5>Ira Membrit</h5>
                    <p class="mb-0">Actor</p>
                </div>
            </li>
            <li class="d-flex align-items-center">
                <img src="static/static/assets/images/page-img/s1.jpg" alt="story-img"
                     class="rounded-circle img-fluid">
                <div class="stories-data ms-3">
                    <h5>Bob Frapples</h5>
                    <p class="mb-0">Doctor</p>
                </div>
            </li>
        </ul>
        <a href="#" class="btn btn-primary d-block mt-3">See More...</a>
    </div>
</div>

app/core/templates/home/trending.html
<div class="card">
    <div class="card-header d-flex justify-content-between">
        <div class="header-title">
            <h4 class="card-title">Trending</h4>
        </div>
        <div class="card-header-toolbar d-flex align-items-center">
            <div class="dropdown">
                <div class="dropdown-toggle" id="dropdownMenuButton" data-bs-toggle="dropdown"
                     aria-expanded="false" role="button">
                    <i class="ri-more-fill h4"></i>
                </div>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton"
                     style="">
                    <a class="dropdown-item" href="#"><i class="ri-eye-fill me-2"></i>View</a>
                    <a class="dropdown-item" href="#"><i
                            class="ri-delete-bin-6-fill me-2"></i>Delete</a>
                    <a class="dropdown-item" href="#"><i class="ri-pencil-fill me-2"></i>Edit</a>
                    <a class="dropdown-item" href="#"><i class="ri-printer-fill me-2"></i>Print</a>
                    <a class="dropdown-item" href="#"><i class="ri-file-download-fill me-2"></i>Download</a>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <ul class="media-story list-inline m-0 p-0">
            <li class="d-flex mb-4 align-items-center ">
                <img src="static/static/assets/images/page-img/s4.jpg" alt="story-img"
                     class="rounded-circle img-fluid">
                <div class="stories-data ms-3">
                    <h5>Web Workshop</h5>
                    <p class="mb-0">1 hour ago</p>
                </div>
            </li>
            <li class="d-flex align-items-center">
                <img src="static/static/assets/images/page-img/s5.jpg" alt="story-img"
                     class="rounded-circle img-fluid">
                <div class="stories-data ms-3">
                    <h5>Fun Events and Festivals</h5>
                    <p class="mb-0">1 hour ago</p>
                </div>
            </li>
        </ul>
    </div>
</div>